version: '3.1'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    ports: 
      - "80:80"
    volumes:
      - .:/app
    links: 
      - db
    

  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080